volumes:
  mysql_data_advisories:

services:
  mysql:
    image: mariadb:10
    volumes:
      - mysql_data_advisories:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: foobar

  wordpress:
    image: thedxw/wpc-wordpress:php8.2
    volumes:
      - .:/usr/src/app
      - ./wp-content:/var/www/html/wp-content
    networks:
      - default
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.advisories.rule=Host(`advisories.localhost`)"
      - "traefik.http.routers.advisories.entrypoints=web"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true
    name: traefik_proxy
