#!/bin/sh
set -e

docker-compose down --remove-orphans
docker-compose pull wordpress

docker compose -p traefik_global -f traefik.yml up -d --no-recreate

if test "$1" = "-d"; then
	docker-compose up -d
else
	docker-compose up
fi
