name: Shellcheck

on: push

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt update
      - run: sudo apt install -y shellcheck
      - run: ./.shellcheck.sh
